eclipse-amlen/amlen

- testTools_scripts/scripts/cluster.py
Added a fix to sort out BVT failures caused by python2 to python3 upgrade in the script to create a cluster
> Put a fix in cluster.py script to cope with python3

- client_plugin/doc/cordovaPluginAPI/mqttCordovaClient.js.html
- client_plugin/jsJSON/js/jsonmsg.js
- server_admin/src/validate_SecurityProfile.c
- server_protocol/Makefile
- server_protocol/src/mqtt.c
- server_protocol/src/mqtt.h
Add in code to pick up protocol extensions so an extension can control if we resubmit retained messages
> Add in code for protocol extensions

- CONTRIBUTING.md
https://www.eclipse.org/projects/tools/documentation.php?id=iot.amlen
> Add CONTRIBUTING.md based on Eclipse Legal Documentation Generator

- server_admin/src/adminHA.c
- server_admin/src/importExport.c
- server_main/scripts/initImaserverInstance.sh
- server_main/scripts/postInstallServer.sh
- server_main/scripts/postUninstallIBMIoTServer.sh
- server_main/scripts/setUserGroup.sh
- server_main/scripts/syncCerts.sh
- server_store/src/storeDiskUtils.c
- server_store/src/storeDiskUtils.h
- server_store/src/storeMemoryHA.c
Description is here:
https://github.com/eclipse/amlen/issues/32
> Update Amlen HA so it understands Message Gateway paths

- CODE_OF_CONDUCT.md
- Documentation/doc_infocenter/com.ibm.ism.doc/Bridge/br00000.dita
- Documentation/doc_infocenter/com.ibm.ism.doc/Planning/pl00040.dita
- Documentation/doc_infocenter/com.ibm.ism.doc/QuickStartGuide/qs00030_.dita
- Documentation/doc_infocenter/com.ibm.ism.doc/TextEntities.dita
- Documentation/doc_infocenter/com.ibm.ism.doc/Upgrading/up00021_.dita
- SECURITY.md
As well as change the version number, update OS prereqs and suggest upgrading to latest Message Gateway ifix before upgrading to Amlen.
> Change docs for Amlen 1.0

- server_build/distrobuild/imawebui.spec
- server_build/docker_build/imawebui-sles.spec
- server_build/docker_build/imawebui.spec
- server_gui/scripts/postInstallWebUI.sh
This adds the which command as a pre-req for the WebUI and adds some extra diagnostics to the log of the postinstall actions carried out when installing the webui
> Ensure `which`cmd installed for webui 

- Jenkinsfile
Links Jenkins and Quay.IO together in an exciting way
> Ib jenkins file

- operator/config/manifests/bases/amlen.clusterserviceversion.yaml
- operator/roles/amlen/defaults/main.yml
- operator/roles/amlen/templates/statefulset.j2
Also added the OwnNamespace install mode to the operator
> Add storageClassName to the statefulset

- Jenkinsfile
remove reliance on dns entry for bvt submissions
> Change to use IP address of BVT machine

- Jenkinsfile
- operator/build/scripts/liveness.py
- operator/build/scripts/monitor.py
- operator/build/scripts/server.py
- operator/config/samples/simple_password.yaml
- operator/roles/amlen/tasks/create_pair.yml
- operator/roles/amlen/templates/statefulset.j2
Add a liveness probe rather than just touching a tile. 
Changed the mount point and name of the admin password for compatability reasons
> Ib.liveness

- operator/roles/amlen/tasks/install.yml
- operator/roles/amlen/templates/statefulset.j2
Add changes to help solve a few of the problems seen when using custom builds
> Fix up mount points for custom builds

- server_proxy/src/pxmhub.c
- server_proxy/src/pxtcp.c
- Added LOG points to for Metaconnection connections. 
- Updated TRACE for Metadata Connection
- Added retry code when creating Metadata Connection failed.
> [patch] Added LOGS and Updated Trace for MHUB Metadata Connection 

- Jenkinsfile
- README.md
- server_build/build_pkg.sh
- server_build/docker_build/Dockerfile.imaserver
- server_build/docker_build/Dockerfile.localRPM.imaserver
Quite a few changes to the Jenkins file to allow you to request the distro from the commit message which complicates things somewhat.Also moves from the default being centos7 to almalinux8
Moves the BVT system from the old push notification to a new pull based system that scans the repository for branches that want a BVT.
> Ib.replicas

- Jenkinsfile
- README.md
- server_build/buildcontainer/Dockerfile.alma8
- server_build/buildcontainer/Dockerfile.alma9
- server_build/buildcontainer/Dockerfile.centos7
- server_build/buildcontainer/Dockerfile.fedora
- server_build/buildcontainer/Jenkinsfile.distro
- server_build/buildcontainer/jenkins.buildalltier1
- server_gui/build.properties
The allbranch pollingbuilds of this branch will fail as the 'latest' versions of the buildcontainers don't contain the updated deps (currently latest points at 1.0.0.8 and the buildcontainers with the updated deps are 1.0.0.9)
> Update WebUI dependencies

- Jenkinsfile
- README.md
- server_build/build_pkg.sh
- server_build/buildcontainer/Dockerfile.alma9
- server_build/buildcontainer/Dockerfile.centos7
- server_build/buildcontainer/Dockerfile.fedora
- server_build/buildcontainer/Jenkinsfile.distro
- server_build/buildcontainer/jenkins.buildalltier1
- server_build/docker_build/imawebui.spec
- server_gui/build.properties
- server_gui/scripts/createAcct.sh
- server_gui/scripts/postInstallWebUI.sh
- server_proxy/src/pxmhub.c
- server_proxy/src/pxtcp.c
- server_utils/src/ismutil.c
- server_utils/test/testTimeUtilsCUnit.c
Fixes include:
*) Changes to kafka reconnect logic:
https://github.com/eclipse/amlen/commit/eaaced8b03aa0d7e8c44511efeb6815669ac27dc
https://github.com/eclipse/amlen/commit/d99d940d7c492434f8325cdf3220dd43f1da0b83
https://github.com/eclipse/amlen/commit/cfd258aa37b53460c22a386a0fdbade0c35119e9
*) Sometimes being unable to find java during install:
https://github.com/eclipse/amlen/commit/4c4c5d2ff8ffc5b8261d99e0a75fda19bb78df94
*) Updating of dependencies for the WebUI:
https://github.com/eclipse/amlen/commit/57b686d2e5cf00f764c8f6851dfb81075fc6383a
> Backport recent fixes from 1.1dev branch to 1.0.0.x branch

- server_proxy_br/src/bridge.c
This is a backport of https://github.com/eclipse/amlen/pull/158
> [patch] Fix SourceQoS setting in kafka bridge

- server_build/build_pkg.sh
- server_build/buildcontainer/Dockerfile.alma8
- server_build/buildcontainer/Dockerfile.alma9
- server_build/docker_build/Dockerfile.imamqttbridge
- server_build/docker_build/Dockerfile.imaserver
- server_build/docker_build/Dockerfile.imawebui
- server_build/docker_build/Dockerfile.localRPM.imaserver
- server_gui/scripts/getUserGroupWebUI.sh
- server_main/scripts/getUserGroup.sh
- server_proxy_br/scripts/getUserGroup.sh
This also changes to use the new amlalinux org
> [minor] Change the default user we run amlen as if none is specified from root to amlen

- operator/config/manager/manager.yaml
I don't really understnad why we seem to duplicate so much stuff and have multiple ways to build everything but I guess it makes sense to someone
> Update manager.yaml to match the version in basis

- Jenkinsfile
variables weren't working properly due to being inside single quotes so switched to directly embedding. 
Also changed from masterBranch to mainBranch to match naming convention.
> Fix jenkins run on main

- server_proxy/src/pxmhub.c
This PR adds more trace when kafka connections are breaking reconnecting. It is trace that is produced at the default trace level (5) so I was initially thinking it was too noisy to deliver to mainline but it only is produced using kafka reconnects and given we've had reports of difficulties during reconnects t seems worth including
> [patch] more diagnostics during kafka reconnects

- operator/Makefile
- operator/config/manifests/bases/eclipse-amlen-operator.clusterserviceversion.yaml
In order to release the operator 1.1.0 we need to move the version on
> move to 1.1.1-a

- operator/Makefile
- operator/config/manifests/bases/eclipse-amlen-operator.clusterserviceversion.yaml
Move version to 1.1.1 ready for release
> Move operator version to 1.1.1 ready for release

- Jenkinsfile
- client_build/build.xml
- client_jms/build.xml
- client_mqtt/build.xml
- client_ra/build.xml
- operator/Makefile
- operator/build/requirements.txt
- operator/config/manifests/bases/eclipse-amlen-operator.clusterserviceversion.yaml
- server_admin/test/admin_test.h
Changes required for almalinux9 mainly dealing with the removal of ant-contrib.
> Move to almalinux9 by default and fix a lot of build.xml to cope with ant-contrib removal

- Jenkinsfile
- server_build/build.xml
- server_build/docker_build/Dockerfile.localRPM.imaproxy
Added cunit-proxy to fvtbuild
Allow specifying the build type through the commit message
change proxy dockerfile to use either curl or curl-minimal
> Fixes for almalinux9

- server_admin/src/ltpautils.c
- server_transport/src/wstcp.c
server_transport encrypt and decrypt functionality changes using openSSL3.0 APIs
Added code under #If OPENSSL_VERSION_NUMBER condition, to support code compilation in ubi8 and ubi9 both images
> Encrypt/Decrypt-ion Functionality Changes Using OpenSSL3.0 APIs 

- Jenkinsfile
- operator/Makefile
- operator/README.md
- operator/config/manifests/bases/eclipse-amlen-operator.clusterserviceversion.yaml
Adjust version of Amlen operator so it is ready for the next release
> [patch] update version of amlen operator

- operator/requirements.yml
Updated Dockerfile and requirements file to use latest versions that patch the critical net/netip vulnerability.
JIRA issue [[IBMIOT-828]](https://jsw.ibm.com/browse/IBMIOT-828)
> Update base image and dependencies to fix net/netip vulnerability
