Documentation/doc_infocenter/com.ibm.ism.doc/Upgrading/up00021_.dita
server_admin/include/config.h
server_main/config/imaBackup.lst
server_main/scripts/initImaserverInstance.sh
server_main/scripts/resetServerConfig.sh
server_main/scripts/setPlatformData.sh
server_main/src/main.c
server_utils/src/execinfo.c

In Message Gateway these two files are under the install directory, we want them under the data dir esp as the install dir is different between MGW and Amlen (and the MGW install dir is removed when MGW is uninstalled).

Move platform.dat and store.init to data dir

---

server_engine/src/clientState.c
server_engine/src/destination.c
server_engine/src/engine.c
server_engine/src/intermediateQ.c
server_engine/src/multiConsumerQ.c
server_engine/src/simpQ.c
server_engine/src/storeMQRecords.c
server_engine/src/topicTree.h
server_engine/src/topicTreeInternal.h
server_engine/src/topicTreeRestore.c
server_engine/src/transaction.c
server_engine/src/transaction.h
server_engine/test/test_transaction.c

Uses the delivererContext to allow holding the read lock on the ACL list during processing of messages using QoS1 or QoS2

Improve QoS1/QoS2 RLAC failover times

---

server_proxy/src/pxtcp.c

This PR contains the changes to allow expired TLS certificate in msproxy for an organization

Allow Expired TLS Certificate in MSPROXY for an Org

---

server_build/buildcontainer/jenkins.updatedownloadwww
websites/download/downloads.css
websites/download/index.html

We need to have a human-readable download page (rather than the auto-generated directory listing). This is the first pass (for 1.0rc1)

Download Page for 1.0rc1

---

Documentation/doc_infocenter/com.ibm.ism.doc/QuickStartGuide/qs00058_.dita

Te download page:
https://download.eclipse.org/amlen/
Mentions that on RHEL8 to install the WebUI you need to enable an extra repository of software but it's not actually mentioned in our docs. 
This adds a short explanation to our docs

[patch] Explain WebUI prereqs needed on RHEL8

---

server_build/build_pkg.sh
server_build/buildcontainer/Dockerfile.fedora

F34 is going out of support, originally planned to change to F36 but that no longer has ant-contrib so change to F35 until we remove our dependency

[minor] change fedora build version to 35 (from 34)

---

server_build/common.mk

Change so when we convert .o files to .u files that we only change the suffix and not every instance of .o

allow .o in branch name

---

Jenkinsfile
server_build/buildcontainer/Jenkinsfile.distro

Pinning the version of the buildcontainers, simplifies updating them... it means we can make a new version of the containers and have one branch test that version without affecting other branches (which will not use the updated container).

[patch] By default use 1.0.0.0 of the buildcontainers

---

server_gui/scripts/postInstallWebUI.sh
server_gui/scripts/preUninstallWebUI.sh
server_gui/scripts/startWebUI.sh

Rather that altering the install files we use liberty env vars to point to the data (altering the install directory causes issues during upgrades and also for k8s/OCP)

[patch] Dont use symlinks in installdir to point to data files

---

server_build/distrobuild/mqcbridge.spec

F35 doesn't like the library path (runpath) we burn into the bridge so it can find the mqclient libraries. 
We've disabled this error for other libraries. I want to revisit our runpath settings but want to unblock the build

Allow MQBridge to build on F35 (in 1.0.0.x branch)

---

README.md
client_build/build.xml
client_jms/build.xml
client_plugin/build.xml
server_admin/src/ltpautils.c
server_build/build_pkg.sh
server_build/buildcontainer/Jenkinsfile.distro
server_build/buildcontainer/build.sh
server_build/buildcontainer/jenkins.buildalltier1
server_cluster/src/MCP_Routing/Util/src/city_c.c
server_plugin/build.xml

This has miscellaneous changes to allow us to work on RHEL9 (actually the clone AlmaLinux 9):
* More cases that relied on ant-contrib that doesn't come with alma9
* Build with Java11 (previously we insisted on Java8)
* change to decrypting LTPA tokens when we were making some dodgy assumptions about buffers that aren't valid on openssl 3.0 (which is what is used in Alma 9)

Allow building on RHEL9

---

server_build/buildcontainer/Jenkinsfile.distro
server_build/buildcontainer/jenkins.buildalltier1
websites/download/index.html

The ChooseDistro job was renamed so updated the BuildAll job to match
Added the distro to the name of the build in ChooseDistro to make it easier to see what builds we are doing
Updated the download page for the links to the alpha

Update downloads page and fixes/improvements for distro build all

---

README.md
server_build/buildcontainer/Dockerfile.alma9

Adds the Dockerfile used to build the amlen-builder for alma9 (a clone of rhel9) and updates the Fedora builder dockerfile to F36.

[patch] Add missing dockerfile for alma9 builder & update to Fedora 36

---

SECURITY.md
client_jms/build.xml
client_mqttv3sample_java/build.xml
client_plugin/build.xml
client_proxy/build.xml
client_ra/build.xml
fvt_MQConnectivity/build.xml
fvt_MQxrscada/build.xml
server_build/distrobuild/imamqttbridge.spec
server_build/distrobuild/imasdk.spec
server_build/distrobuild/imaserver.spec
server_build/distrobuild/imawebui.spec
server_build/distrobuild/mqcbridge.spec
server_build/distrobuild/protocolplugin.spec
svt_client_tests/build.xml
testTools_CLI_Utils/build.xml
testTools_DriverSync/build.xml
testTools_JCA/build.xml
testTools_JCAra/build.xml
testTools_JMSTestDriver/build.xml
testTools_MQ_MQTTClient/build.xml
testTools_MqttTest/build.xml

Updates that:
Update to compiling to java bytecode for Java 1.8 and above (as on some newer Java SDKs that is the earliest that can be targeted).
Update which packages are build pre-reqs for some of the non-default components so they can be built on Fedora 36.

Update to targetting Java 1.8 and fix some prereq includes

---

Documentation/doc_infocenter/com.ibm.ism.doc/Monitoring/admin00027.dita

Doc updates based on feedback on slack:
https://eclipse-iot-wg.slack.com/archives/C0206GDEKFC/p1661352173086139

[patch] Mention REST lists of clients only include disconnected clients by default

---

server_build/build.sh
server_build/build_pkg.sh
server_proxy/src/javaconfig.c
server_tmsmsgtool/nut_translations/nut_msgtoolwrapper.py
server_tmsmsgtool/nut_translations/nut_xsltprocwrapper.py

gcc now reports that the spidercast component uses lots of deprecated C++. Temporarily we have to suppress these warnings from the screen to stop builds failing with overly long logs.
I've also made some updates so the translation works with older version of python (3.6) and so we look in more places for a JVM is we need one.

Updates from moving to a more recent compiler

---

operator/roles/amlen/tasks/create_pair.yml
operator/roles/amlen/templates/statefulset.j2

- Added optional imagePullSecret to allow operator to pull from private repositories
- Added options to override directories used in the amlen pod
- Split out the apply steps in operator for loadbalancer, statefulset and networkpolicy to make it easier to work out which has failed

Add more customization options to the operator to support 3rd party builds of amlen

---

operator/roles/amlen/defaults/main.yml
operator/roles/amlen/tasks/create_pair.yml
operator/roles/amlen/templates/statefulset.j2

Adds _amlen_topology_spread_contraints_when_unsatisfiable to allow the crd to specify that multi zone must be enforced
Also fixes up some certificate issues

Add topologySpreadConstraint to allow multi AZ zones

---

websites/download/index.html

I have had a slack comment and an email by people confused about whether 1.1 is release so updated the downloads page to clarify a bit.

Downloads Page: Clarify which releases are actually released

---

operator/config/manifests/bases/eclipse-amlen-operator.clusterserviceversion.yaml

Some of the CSV fields hadn't been updated to match those in the operator hub meaning if you install it manually from the bundle it wouldn't be compatible. Long term we need to ensure they match or see if there is another way to do it so we don't have the operator bundle in quay.io and a second one hidden away in operator hub.

update csv for manual installation

---

server_proxy/src/pxmhub.c

- Added additional code to create Metadata Connection and request Metadata connection (if the Metadata process haven't started already) when publishing events failed. 
- Fixed a bug which metadata uses transport object for Data Connection

[patch] Added code to request Metadata when publish failed

---

operator/build/scripts/monitor.py
operator/build/scripts/readiness.py
operator/build/scripts/server.py
operator/roles/amlen/library/recover.py
operator/roles/amlen/tasks/create_pair.yml
operator/roles/amlen/templates/statefulset.j2
server_build/docker_build/Dockerfile.imaserver
server_build/docker_build/Dockerfile.localRPM.imaserver

Allow passing a fully qualified name to the statefulset which means that it's possibe to pass a digest rather than having an image tag.
Added recovery code into the operator to detect a scenario where only a single pod is active but has not reached running state due to waiting for the partner but the statefulset will not expand so we hit a stalemate. This occurs if both pods are deleted at the same time.

Support digests and auto recovery of statefulset

---

operator/config/manifests/bases/eclipse-amlen-operator.clusterserviceversion.yaml

Change the operator version in the bundle from the alpha v1.0.1a to v1.0.1
This doesn't impact the version used when installing from the redhat catalog as that is dependant on the version specified in https://github.com/redhat-openshift-ecosystem/community-operators-prod
This allows others to build catalogs by pointing at the bundle stored in:
https://quay.io/repository/amlen/operator-bundle

update operator version number

---

server_protocol/src/jms.c
server_utils/include/commonMemHandlerTypes.h
server_utils/src/array.c
server_utils/src/commonMemHandler.c
server_utils/src/filter.c
server_utils/src/ismlist.c
server_utils/src/logformat.c
server_utils/src/logwriter.c
server_utils/src/map.c
server_utils/src/properties.c
server_utils/src/rehash.c
server_utils/src/selector.c
server_utils/src/ssl.c
server_utils/src/throttle.c
server_utils/src/trace.c
server_utils/src/xmlparser.c

This change adds more categories of memory that we allocate from and track (at the moment there is a large server_utils_misc category) and this will help us figure out what Amlen is using memory for,

[patch] break up the utils_default memory category

---

server_proxy/src/pxmhub.c

When the metadata connection to kafka is broken, currently (in some cases) it does not recover and reestablish the connection successfully

adapt to kafka leadership changes more smoothly

---

operator/roles/amlen/tasks/create_pair.yml

If a statefulset is deleted the replicasready field is not defined until at least one pod is ready. We need the recovery code to kick in before then so just wait till the replicas field is defined so we know how many it should have.

dont wait for replicasReady to be defined in recovery code

---

server_admin/src/authentication.c
server_utils/include/ismutil.h
server_utils/include/sasl_scram.h
server_utils/src/sasl_scram.c

We were leaking memory when we hashed a password when authenticating an admin request. The area has been reworked slightly to avoid allocating the memory in the first place.

[patch] fix memory leak in hashing admin user password

---

Jenkinsfile

If a merge into main has squashed multiple commits that were running non standard builds into the comment then the build could end up doing anything so for builds of main ignore them and just use the defaults.

For main always use default distro and build

---

server_build/build_pkg.sh
server_build/docker_build/imawebui.spec
server_gui/scripts/createAcct.sh
server_gui/scripts/postInstallWebUI.sh

This is a bit hacky. 
If there is no JVM on the system and a JVM and amlen-webui are installed in the same rpm transaction, then on RHEL8 systems, that JVM is often not the default JVM for the system (i.e. /usr/bin/java is not a symlink to it) during the post install phase of the transaction.
I /think/ this is a bug in the rpm at this vintage - but we would around it by - if no java is in the path when we wanting to use it - dumping to our log some interesting directories and then explicitly setting a path to the JVM we have pre-reqd.

[patch] Cope with java not being in path during post-install by guessing java path

---

server_utils/src/ismutil.c
server_utils/test/testTimeUtilsCUnit.c

https://www.uuidtools.com/uuid-versions-explained Explains that a type 1 uuid is of the form
LLLLLLLL-MMMM-VHHH-RSSS-NNNNNNNNNNNN
Where:
L  = Low Time
M =  Mid Time
V = Version (1)
H = High Time
R = Variant (in range 8-b inclusive as is starts 0b10......)
S = Sequence number
N = Node
*NB* Each Letter is a nibble (hex digit) not a byte
With the code as it stands in the high bits of the node are set, it is or'd in with the bytes that are used for the RSSS - i.e. corrupting the sequence number or even the variant.
This is a tiny fix that ensures the 4 nibbles (two bytes) that are reserved for the sequence number+variant are not or'd with the node.

[patch] node is overriding variant and sequence number in uuids

---

server_proxy_br/src/bridge.c

There is a setting that allows the maximum qos the imabridge uses when it makes a subscription to be controlled. Currently this setting is broken and the bridge always subscribes with maxqos=2.
This is a 1-character change that makes the sourceqos setting in the bridge work.

[patch] Fix SourceQoS setting in kafka bridge

---

operator/config/default/manager_auth_proxy_patch.yaml
operator/config/manifests/bases/eclipse-amlen-operator.clusterserviceversion.yaml

We were not setting the WATCH_NAMESPACES environment variable which means even when installing in namepsace scope it was effectivly running at cluster level. Also increasing memory as we've seen cases where the default wasn't enough.

Updates to the operator

---

operator/Makefile
operator/config/manifests/bases/eclipse-amlen-operator.clusterserviceversion.yaml

From the readme:
> The release process is currently a bit awkward what needs to happen is:
> 
> push a change that moves the version from the current alpha version to the actual version, ie if the version is 1.0.3-a then submit a PR to change it to version 1.0.3
> 
> When that has merged into main and completed the build:
> 
>     Tag the operator-bundle:main-d as version-pre eg 1.0.3-pre
>     Tag the operator:main as v1.0.3
> 
> Push a change that moves the version in main to the next alpha channel eg 1.0.4-a
> 
> When that has merged into main and completed the build:
> 
>     Tag the operator-bundle:(version)-pre as (version) eg add 1.0.3 tag to the 1.0.3-pre tag
> 
> This results in:
> 
>     operator-bundle:main which points to operator-bundle:main with a version of 1.0.4-a (can be …

New operator release 1.0.3

---

Jenkinsfile
operator/Makefile
operator/config/manager/manager.yaml

We produce two bundles of the operator one that uses digests which allows disconnected installs (airgap) and one that uses tags which is typically for development systems but both had the same version so if you tried t oadd both to a custom catalog they would overwrite each other so you only ended up with the last one added.
Also found another place where we need to specify the memory and watch namespaces (I suspect we have redundant files that need tidying up or can be combined somehow)

Add a suffix to the version for the dev build to distinguish it from digest build

---

operator/Makefile
operator/config/manager/manager.yaml
operator/config/manifests/bases/eclipse-amlen-operator.clusterserviceversion.yaml
operator/roles/amlen/tasks/main.yml

From readme:
> The release process is currently a bit awkward what needs to happen is:
> 
> push a change that moves the version from the current alpha version to the actual version, ie if the version is 1.0.3-a then submit a PR to change it to version 1.0.3
> 
> When that has merged into main and completed the build:
> 
>     Tag the operator-bundle:main-d as version-pre eg 1.0.3-pre
>     Tag the operator:main as v1.0.3
> 
> Push a change that moves the version in main to the next alpha channel eg 1.0.4-a
> 
> When that has merged into main and completed the build:
> 
>     Tag the operator-bundle:(version)-pre as (version) eg add 1.0.3 tag to the 1.0.3-pre tag
> 
> This results in:
> 
>     operator-bundle:main which points to operator-bundle:main with a version of 1.0.4-a (can be used …

Move operator to 1.0.4a

---

Jenkinsfile
server_build/buildcontainer/Dockerfile.alma8
server_build/buildcontainer/Dockerfile.alma9

As part of a build identify if the buildcontainer images have changed and behave appropriately. It works using special builder-update tags in git, for example main-builder-update always points at the last commit in main that changed one of the buildcontainer dockerfiles. 
For branch/PR builds it checks to see if there is a builder-update tag on that branch, if so it checks if there have been further updates, if there is no builder-update tag it will compare with the main-builder-update tag. If there are changes a new branch specific builder-update tag is created and a quayIO build of the buildcontainer is run.
For main it checks to see if any buildcontainer docker file has changed since the last main-builder-update tag, if so all distros will be rebuilt (regardless of if that specific …

Automatically rebuild the build containers as required

---

server_proxy/src/pxmhub.c

Kafka in MSK seems to number the nodes starting from 1 (rather than 0). The kafka metadata processing previously refused to connect to a leader not in the range 0 <= leaderid < broker_count

[patch] fix bug in processing kafka metadata from MSK

---

server_proxy/test/proxy_test.c

Some of the recent changes to the linking seem to have changed slightly the timing of a microbenchmark that a unit test relies on and the unit tests therefore fail intermittently

[patch] fix intermittent unit test failure

---

server_proxy/test/proxy_test.c

Now we disable client activity by default - we are seeing an issue in a test that is still run when it is disabled

[patch] only run client activity test when activity is compiled in

---

server_admin/src/ltpautils.c

couple of openSSL APIs deprecated in openSSL3.0 (in ubi9 image), as of now those are exposed but sooner or later we won't see those.
This PR contains code change towards that for LTPA util file, where I've replaced RSA key with EVP_PKEY and couple of other deprecated APIs (eg. RSA_new and RSA_private_encrypt) replaced with newly introduced APIs using EVP_PKEY.

OpenSSL 3.0 Support : Replaced RSA with EVP_PKEY in LTPA utils

---

operator/roles/amlen/library/configure.py

We see occasional failures in testing the operator. I think it is because there is a short window where the operator puts a server into maintenance mode and if the operator is restarted/fails in that window it doesn't try to take it out of maintenance mode.
This change means that the operator attempts to move servre in maintenance into production mode

[patch] ensure operator gets amlens out of maintenance

---

operator/Dockerfile

Updated Dockerfile and requirements file to use latest versions that patch the critical net/netip vulnerability.
JIRA issue [[IBMIOT-828]](https://jsw.ibm.com/browse/IBMIOT-828)

Update base image and dependencies to fix net/netip vulnerability

---

server_snmp/src/imaSnmpAgentInit.c

Small tidy up that prevents building on a modern gcc (like is used in rhel10)

[patch] ism_threadh_t is a number not a pointer (error on Fedora 42)
